name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  generate-snake:
    name: Generate Snake Contribution Grid
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Gera a animação do Snake em SVG e PNG (fallback)
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: thelipesousa
          outputs: |
            dist/github-snake.svg
            dist/github-snake.png

      # Exibir estrutura do diretório para depuração
      - name: Show directory structure
        run: ls -R dist

      # Commit e push dos arquivos gerados
      - name: Commit and Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated Snake animation"
          add: "dist/github-snake.svg dist/github-snake.png"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Faz deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
