name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 */12 * * *" # Roda a cada 12 horas
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: thelipesousa
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.svg?palette=github-light

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
